config/routes.rb
Player1orlando::Application.routes.draw do
  
  devise_for :admins
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  
  get '/rewards/redemption', to: 'rewards#redeem', as: 'redeem_reward'
  get '/vip/checkin/process', to: 'pages#process_vip_checkin', as: 'process_vip_checkin'
  post '/rewards/redeem', to: 'rewards#post_redeem', as: 'post_redeem_reward'
  post '/rewards/post_user_redeem', to: 'rewards#post_user_redeem', as: 'post_user_redeem_reward'
  post '/citizen/checkin/process', to: 'rewards#post_citizen_checkin', as: 'post_citizen_checkin_reward'
  post '/membership/process', to: 'pages#process_memberships', as: 'process_memberships'
  
  get '/rate/drink/:id/:rating', to: 'ratings#set_rating', as: 'set_rating'
  get '/rate/game/:id/:rating', to: 'ratings#set_game_rating', as: 'set_game_rating'
  get '/rewards/issue/:id', to: 'rewards#issue', as: 'issue_reward'
  get '/d/:code/:user_id', to: 'rewards#user_redeem', as: 'user_redeem'
  
  get '/beverages/', to: 'categories#index', as: 'beverages', :defaults => { :area => 'drinks' }

  get '/beverages/dispense/:dispense_type', to: 'beverages#show_by_dispense_type', as: 'dispense_beverages'
  get '/beverages/updates/:update_style', to: 'beverages#show_by_update_style', as: 'update_beverages'
  get '/beverages/printable/:dispense_type', to: 'beverages#show_by_printable', as: 'printable_beverages'
  get '/beverages/printable/:dispense_type/:dispense_type2', to: 'beverages#show_by_printable', as: 'printable_beverages2'
  get '/beverages/printable/:dispense_type/:dispense_type2/:dispense_type3', to: 'beverages#show_by_printable', as: 'printable_beverages3'
  get '/beverages/printable_custom/:view_options', to: 'beverages#show_by_printable_custom', as: 'printable_custom'

  get '/beverages/hidden', to: 'categories#allhidden', as: 'hidden_beverages', :defaults => { :area => 'drinks' }
  get '/play/', to: 'categories#index', as: 'play', :defaults => { :area => 'games' }
  get '/play/hidden', to: 'categories#allhidden', as: 'hidden_play', :defaults => { :area => 'games' }
  
  get '/manual/info', to: 'pages#info', as: 'infos_page'
  get '/manual/vips', to: 'pages#vips', as: 'vips_page'
  get '/manual/citizens', to: 'pages#rewards', as: 'rewards_page'
  get '/manual/rules', to: 'pages#rules', as: 'rules_page'
  get '/manual/terms', to: 'pages#terms', as: 'terms_page'
  get '/manual/privacy', to: 'pages#privacy', as: 'privacy_page'
  get '/feed', to: 'pages#feed', as: 'feed_rss'
  get '/happyhour', to: 'pages#happyhour', as: 'happy_hour_page'
  get '/food', to: 'pages#food', as: 'food_page'
  get '/music', to: 'pages#music', as: 'music_page'
  get '/bartender_choice', to: 'pages#bartender_choice', as: 'bartender_choice_page'
  get '/leaderboard', to: 'pages#leaderboard', as: 'leaderboard_page'

  get '/tvboards/draft', to: 'taps#tvboard', as: 'tvboard_draft_page'
  get '/tvboards_hor/draft', to: 'taps#tvboard_hor', as: 'tvboard_hor_draft_page'
  get '/tvboards/bottle/:id', to: 'drinks#tvscreen', as: 'tvboard_bottle_page'

  get '/drinks/all/edit', to: 'drinks#edit_all', as: 'edit_all_drinks'
  put '/drinks/all', to: 'drinks#update_all', as: 'update_all_drinks'

  
  resources :users, :only => [:show, :index, :edit, :update, :destroy]
  resources :katy_corners, :path => "katys"
  resources :trackers, :path => "drink_tracker" do
    member do
      get 'track'
      post 'point_track'
    end
  end
  resources :categories, :beer_styles, :drinks, :games, :events, :galleries
  resources :taps
  
  
  get '/citizen/checkin', to: 'pages#citizen_checkin', as: 'citizen_checkin'
  resources :rewards, :path => "citizen" do
    member do
      # get 'redeem'
      # post 'post_redeem'
      # post 'post_citizen_checkin'
    end
  end

  
  
  root 'pages#index'
end

app/models/beer_style.rb
class BeerStyle < ActiveRecord::Base
  has_many :drinks
  
  validates :name, :description, presence: true
  
end

app/controllers/beer_styles_controller.rb
class BeerStylesController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_beer_style, only: [:show, :edit, :update, :destroy]

  def index
    @beer_styles = BeerStyle.order(name: :asc).all
  end

  def show
  end

  def new
    @beer_style = BeerStyle.new
  end

  def edit
  end

  def create
    @beer_style = BeerStyle.new(beer_style_params)

    respond_to do |format|
      if @beer_style.save
        format.html { redirect_to @beer_style, notice: 'Beer style was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @beer_style.update(beer_style_params)
        format.html { redirect_to @beer_style, notice: 'Beer style was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @beer_style.destroy
    respond_to do |format|
      format.html { redirect_to beer_styles_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_style
      @beer_style = BeerStyle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_style_params
      params.require(:beer_style).permit(:name, :description)
    end
end

app/helpers/beer_styles_helper.rb
module BeerStylesHelper
end

app/views/beer_styles/_form.html.erb
<%= form_for(@beer_style) do |f| %>
  <% if @beer_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_style.errors.count, "error") %> prohibited this beer_style from being saved:</h2>

      <ul>
      <% @beer_style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h4>You know what you got to do.<small>All fields are required.</small></h4>
<div class="dq-form">
	<div class="field10-10"><%= f.text_field :name, :placeholder => "Category Name" %></div>
	<div class="field10-10"><%= f.text_area :description, :placeholder => "Description", :rows => 7 %></div>

	<div class="dq-buttons">
		<%= f.submit :value => "#{params[:action].humanize} Beer Style" %>
	</div>
</div>

<% end %>

app/views/beer_styles/edit.html.erb
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-pencil"></i> Edit Beer Style <small>Filling out forms are great.</small></h2></div>
	<div class="span8-12">
		<%= render 'form' %>
	</div>

	<div class="span4-12">
		<h5>Admin Options</h5>
		<div class="dq-buttons">
			<%= link_to 'Show', @beer_style, :class => "lnk-button full" %>
			<%= link_to 'Back', beer_styles_path, :class => "lnk-button full" %>
		</div>
	</div>
</div>

app/views/beer_styles/index.html.erb
<% title "Beer Styles" %>

<!-- Standard Content -->
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-beer"></i> Beer Styles<small>There is more than you know.</small></h2></div>

	<div class="span8-12">
		<ul class="unstyled lined">
			<% @beer_styles.each do |beer_style| %>
				<% if admin_signed_in? -%>
					<li>
						<div class="float-right"><%= link_to 'Edit', edit_beer_style_path(beer_style) %> | <%= link_to 'Destroy', beer_style, method: :delete, data: { confirm: 'Are you sure?' } %></div>
						<strong class="large"><%= link_to beer_style.name, beer_style -%></strong>
					</li>
				<% else %>
					<% if beer_style.drinks.where(:visible => true).count > 0 %>
					<li>
						<strong class="large"><%= link_to beer_style.name, beer_style -%></strong>
					</li>
					<% end %>
				<% end %>
			<% end %>
		</ul>
	</div>

	<div class="span4-12">
		<% if admin_signed_in? %>
		<h5>Admin Options</h5>
		<div class="dq-buttons pad-bottom">
			<%= link_to 'New Beer style', new_beer_style_path, :class => "lnk-button full" %>
		</div>
		<% end %>
		<%= render 'shared/whycraft' %>
	</div>
	
</div>

app/views/beer_styles/index.mobile.erb
<% title "Beer Styles" %>

<!-- Standard Content -->
<div class="content">
	<div class="span12-12"><h3><i class="fa fa-beer"></i> Beer Styles<small>There is more than you know.</small></h3></div>

	<div class="span8-12">
		<ul class="unstyled lined">
			<% @beer_styles.each do |beer_style| %>
				<% if admin_signed_in? -%>
					<li>
						<div class="float-right"><%= link_to 'Edit', edit_beer_style_path(beer_style) %> | <%= link_to 'Destroy', beer_style, method: :delete, data: { confirm: 'Are you sure?' } %></div>
						<strong class="large"><%= link_to beer_style.name, beer_style -%></strong>
					</li>
				<% else %>
					<% if beer_style.drinks.where(:visible => true).count > 0 %>
					<li>
						<strong class="large"><%= link_to beer_style.name, beer_style -%></strong>
					</li>
					<% end %>
				<% end %>
			<% end %>
		</ul>
	</div>
	
</div>

app/views/beer_styles/new.html.erb
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-pencil"></i> Create Beer Style <small>Filling out forms area great.</small></h2></div>
	<div class="span8-12">
		<%= render 'form' %>
	</div>

	<div class="span4-12">
		<h5>Admin Options</h5>
		<div class="dq-buttons">
			<%= link_to 'Back', beer_styles_path, :class => "lnk-button full" %>
		</div>
	</div>
</div>

app/views/beer_styles/show.html.erb
<% title @beer_style.name %>

<div class="content">
	<div class="span12-12"><h2><i class="fa fa-beer"></i> Beer Styles<small>What means what?</small></h2></div>
	<div class="span8-12">
		<h4><%= @beer_style.name -%><small>This is what is all means.</small></h4>
		<%= simple_format @beer_style.description -%>

		
		<% if @beer_style.drinks.where(:visible => true).count > 0 %>
		<h4>Beers that we serve<small>Here are some beers that we have that are this style.</small></h4>		
		<ul class="unstyled">
			<% @beer_style.drinks.where(:visible => true).order(name: :asc).limit(10).each do |drink| %>
				<li><strong class="large"><%= link_to drink.name, drink_path(drink) -%></strong><%= simple_format drink.description -%></li>
			<% end %>
		</ul>
		<% end %>

	</div>

	<div class="span4-12">
		<div class="dq-buttons pad-bottom">
			<%= link_to 'Go Back to Beer Styles', beer_styles_path, :class => "lnk-button full" %>
			<%= link_to 'Go Back to Beverages', beverages_path, :class => "lnk-button full" %>
		</div>
		<%= render 'shared/whycraft' %>
	</div>
</div>

app/views/beer_styles/show.mobile.erb
<% title @beer_style.name %>

<div class="content">
	<div class="span12-12"><h3><i class="fa fa-beer"></i> Beer Styles<small>What means what?</small></h3></div>
	<div class="span12-12">
		<h4><%= @beer_style.name -%><small>This is what is all means.</small></h4>
		<%= simple_format @beer_style.description -%>

		
		<% if @beer_style.drinks.where(:visible => true).count > 0 %>
		<h4>Beers that we serve<small>Here are some beers that we have that are this style.</small></h4>		
		<ul class="unstyled">
			<% @beer_style.drinks.where(:visible => true).order(name: :asc).limit(10).each do |drink| %>
				<li><strong class="large"><%= link_to drink.name, drink_path(drink) -%></strong><%= simple_format drink.description -%></li>
			<% end %>
		</ul>
		<% end %>

	</div>

	<div class="span12-12">
		<div class="dq-buttons pad-bottom">
			<%= link_to 'Go Back to Beer Styles', beer_styles_path, :class => "lnk-button full" %>
			<%= link_to 'Go Back to Beverages', beverages_path, :class => "lnk-button full" %>
		</div>
	</div>
</div>