config/routes.rb
Player1orlando::Application.routes.draw do
  
  devise_for :admins
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  
  get '/rewards/redemption', to: 'rewards#redeem', as: 'redeem_reward'
  get '/vip/checkin/process', to: 'pages#process_vip_checkin', as: 'process_vip_checkin'
  post '/rewards/redeem', to: 'rewards#post_redeem', as: 'post_redeem_reward'
  post '/rewards/post_user_redeem', to: 'rewards#post_user_redeem', as: 'post_user_redeem_reward'
  post '/citizen/checkin/process', to: 'rewards#post_citizen_checkin', as: 'post_citizen_checkin_reward'
  post '/membership/process', to: 'pages#process_memberships', as: 'process_memberships'
  
  get '/rate/drink/:id/:rating', to: 'ratings#set_rating', as: 'set_rating'
  get '/rate/game/:id/:rating', to: 'ratings#set_game_rating', as: 'set_game_rating'
  get '/rewards/issue/:id', to: 'rewards#issue', as: 'issue_reward'
  get '/d/:code/:user_id', to: 'rewards#user_redeem', as: 'user_redeem'
  
  get '/beverages/', to: 'categories#index', as: 'beverages', :defaults => { :area => 'drinks' }

  get '/beverages/dispense/:dispense_type', to: 'beverages#show_by_dispense_type', as: 'dispense_beverages'
  get '/beverages/updates/:update_style', to: 'beverages#show_by_update_style', as: 'update_beverages'
  get '/beverages/printable/:dispense_type', to: 'beverages#show_by_printable', as: 'printable_beverages'
  get '/beverages/printable/:dispense_type/:dispense_type2', to: 'beverages#show_by_printable', as: 'printable_beverages2'
  get '/beverages/printable/:dispense_type/:dispense_type2/:dispense_type3', to: 'beverages#show_by_printable', as: 'printable_beverages3'
  get '/beverages/printable_custom/:view_options', to: 'beverages#show_by_printable_custom', as: 'printable_custom'

  get '/beverages/hidden', to: 'categories#allhidden', as: 'hidden_beverages', :defaults => { :area => 'drinks' }
  get '/play/', to: 'categories#index', as: 'play', :defaults => { :area => 'games' }
  get '/play/hidden', to: 'categories#allhidden', as: 'hidden_play', :defaults => { :area => 'games' }
  
  get '/manual/info', to: 'pages#info', as: 'infos_page'
  get '/manual/vips', to: 'pages#vips', as: 'vips_page'
  get '/manual/citizens', to: 'pages#rewards', as: 'rewards_page'
  get '/manual/rules', to: 'pages#rules', as: 'rules_page'
  get '/manual/terms', to: 'pages#terms', as: 'terms_page'
  get '/manual/privacy', to: 'pages#privacy', as: 'privacy_page'
  get '/feed', to: 'pages#feed', as: 'feed_rss'
  get '/happyhour', to: 'pages#happyhour', as: 'happy_hour_page'
  get '/food', to: 'pages#food', as: 'food_page'
  get '/music', to: 'pages#music', as: 'music_page'
  get '/bartender_choice', to: 'pages#bartender_choice', as: 'bartender_choice_page'
  get '/leaderboard', to: 'pages#leaderboard', as: 'leaderboard_page'

  get '/tvboards/draft', to: 'taps#tvboard', as: 'tvboard_draft_page'
  get '/tvboards_hor/draft', to: 'taps#tvboard_hor', as: 'tvboard_hor_draft_page'
  get '/tvboards/bottle/:id', to: 'drinks#tvscreen', as: 'tvboard_bottle_page'

  get '/drinks/all/edit', to: 'drinks#edit_all', as: 'edit_all_drinks'
  put '/drinks/all', to: 'drinks#update_all', as: 'update_all_drinks'

  
  resources :users, :only => [:show, :index, :edit, :update, :destroy]
  resources :katy_corners, :path => "katys"
  resources :trackers, :path => "drink_tracker" do
    member do
      get 'track'
      post 'point_track'
    end
  end
  resources :categories, :beer_styles, :drinks, :games, :events, :galleries
  resources :taps
  
  
  get '/citizen/checkin', to: 'pages#citizen_checkin', as: 'citizen_checkin'
  resources :rewards, :path => "citizen" do
    member do
      # get 'redeem'
      # post 'post_redeem'
      # post 'post_citizen_checkin'
    end
  end

  
  
  root 'pages#index'
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :discounts, :dependent => :destroy
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :authenticate_user!, only: [:issue, :redeem, :post_redeem]
  before_action :set_reward, only: [:show, :edit, :update, :destroy, :issue]
  
  layout :resolve_layout

  def index
    @user_rewards = nil

    unless admin_signed_in?
      if current_user.membership_number.blank?    
        @user = current_user
        if @user.nil?
          redirect_to new_user_session_path
        else
          @user_rewards = Discount.where(:used => false, :user_id => @user)
        end
      else
        redirect_to root_path
      end
    end

    @rewards = Reward.where(:visible => true).order(points: :asc)
    @inactive_rewards = Reward.where(:visible => false).order(points: :asc)
  end

  def new
    @reward = Reward.new(:visible => true, :points => 10)
  end

  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to rewards_path, notice: 'Reward was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to rewards_path, notice: 'Reward was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end
  
  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
    end
  end
  
  
  def issue
    @user = current_user
    
    # unless citizen_allowed?
    #   redirect_to rewards_path, alert: "Sorry can't earn points on select days. This is one of them"
    # else
      if (@user.lifetime_points - @user.used_points) >= @reward.points && @user.has_membership?
        discount = Discount.create(
          :reward_id => @reward.id,
          :used => false,
          :user_id => @user.id,
          :points => @reward.points
        )
        new_point_balance = @user.used_points + @reward.points
      
        @user.update(:used_points => new_point_balance)
      
        redirect_to rewards_path, notice: "Cool you were issed this reward. To use it just tell us the code (#{sprintf('%06d', discount.code)}) or have your friend tell us the code."
      else
        redirect_to rewards_path, alert: 'Sorry you don\'t have enough points for that reward or your not a citizen yet.'
      end
    # end
    
  end
  
  def redeem
    unless current_user.emp_code.blank?
    else
      redirect_to rewards_path
    end
  end
  
  def post_redeem
    if current_user.emp_code.blank?
      redirect_to rewards_path
    else
      @discount = Discount.where(:code => params[:code]).first
      if @discount.nil?
        redirect_to redeem_reward_path, alert: "Not a valid code."
      elsif @discount.used == true
        redirect_to redeem_reward_path, alert: "Code already used."
      else
        @discount.update(:used => true)
        redirect_to redeem_reward_path, notice: "Success: Redeemed '#{@discount.reward.name}'. "
      end
    end
  end
  
  def post_user_redeem
    @discount = Discount.where(:code => params[:code], :user_id => params[:user_id]).first
    if @discount.nil?
      redirect_to user_redeem_path(params[:code], params[:user_id]), alert: "Not a valid code."
    else
      @discount.update(:used => true)
      redirect_to root_path, notice: "Success: Redeemed '#{@discount.reward.name}'. "
    end
  end
  
  def user_redeem
    @discount = Discount.where(:code => params[:code], :user_id => params[:user_id]).first
    if @discount.nil?
      redirect_to redeem_reward_path, alert: "Not a valid code."
    end
  end
  
  def post_citizen_checkin
    # if current_user.emp_code.blank?
        # redirect_to rewards_path
    if !current_user.emp_code.blank? || params[:from_user].present?
      @user = User.find(params[:code])
      if @user.nil?
        redirect_to redeem_reward_path, alert: "Not a valid user code."
      else
        if @user.has_membership?
          if @user.timelines.where(:nature => "checkin").where(:created_at => Time.zone.now.beginning_of_day...Time.zone.now.end_of_day).count > 0
            redirect_to root_path, alert: "Alert: Already checked in."
          else
            timeline = Timeline.create(
              :user_id => @user.id,
              :nature => "checkin"
            )
                      
            user_visit_count = @user.timelines.where(:nature => "checkin").count
            if user_visit_count == 10
              @user.add_badge(8)
            elsif user_visit_count == 20
              @user.add_badge(9)
            elsif user_visit_count == 50
              @user.add_badge(10)
            elsif user_visit_count == 100
              @user.add_badge(11)
            elsif user_visit_count == 200
              @user.add_badge(12)
            elsif user_visit_count == 500
              @user.add_badge(13)
            end
          
            if params[:from_user].present?
              new_point_balance = @user.lifetime_points + 3
              @user.update(:lifetime_points => new_point_balance)
              redirect_to citizen_checkin_path, notice: "Success: Valid Checkin '#{@user.first_name}'. "
            else
              new_point_balance = @user.lifetime_points + 3
              @user.update(:lifetime_points => new_point_balance)
              redirect_to redeem_reward_path, notice: "Success: Valid Checkin '#{@user.first_name}'. "
            end
          end
        else
          redirect_to redeem_reward_path, alert: "Not a valid citizen."
        end
      end
    else
      redirect_to rewards_path
    end
  end
  
  private
    def set_reward
      @reward = Reward.find(params[:id])
    end

    def reward_params
      params.require(:reward).permit(:name, :description, :points, :visible)
    end
    
    def resolve_layout
      case action_name
      when "redeem"
        "redeem_app"
      else
        "application"
      end
    end
  
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
	<% if @reward.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

	    <ul>
	    <% @reward.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	
	<h4>You know what you got to do.<small>All fields are required.</small></h4>
	<div class="dq-form">
		<div class="field6-10 has-labels"><%= f.text_field :name, :placeholder => "Reward Name" %></div>
		<div class="field2-10"><%= f.label :points -%><%= f.number_field :points, :placeholder => "Points" %></div>
		<div class="field2-10 has-labels"><%= f.check_box :visible %><%= f.label :visible, "Visible?" %></div>
		<div class="field10-10"><%= f.text_area :description, :placeholder => "Description", :rows => 7 %></div>

		<div class="dq-buttons">
			<%= f.submit :value => "#{params[:action].humanize} Reward" %>
		</div>
	</div>

<% end %>

app/views/rewards/edit.html.erb
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-pencil"></i> Edit Reward <small>Filling out forms are great.</small></h2></div>
	<div class="span8-12">
		<%= render 'form' %>
	</div>

	<div class="span4-12">
		<h5>Admin Options</h5>
		<div class="dq-buttons">
			<%= link_to 'Go Back to Rewards', rewards_path, :class => "lnk-button full back" %>
			<%= link_to 'Destroy Reward', @reward, method: :delete, data: { confirm: 'Are you sure? This will destory all items under this category as well. It is recommended to just change the visibilty of the category.' }, :class => "lnk-button full cancel delete" %>
		</div>
	</div>
</div>

app/views/rewards/index.html.erb
<% title "Rewards" %>
<!-- Standard Content -->
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-trophy"></i> Player 1 Citizen<small>Your part of a special group.</small></h2></div>

	<div class="span8-12">
		<% unless admin_signed_in? %>
		<% if user_signed_in? && @user_rewards.size > 0 %>
			<h4>Your Rewards<small>These are the rewards you chose.</small></h4>		
			<ul class="unstyled lined pad">
				<% @user_rewards.each do |user_reward| %>
					<li>
						<strong class="large">
							<div class="float-right">Code: <%= sprintf('%06d', user_reward.code) -%></div>
							<%= user_reward.reward.name -%>
						</strong><br/>
						Copy link to share: <%= link_to user_redeem_url(user_reward.code, user_reward.user_id), user_redeem_url(user_reward.code, user_reward.user_id) -%>
					</li>
				<% end %>
			</ul><br/>
		<% end %>
		<% end %>

		<h4>Rewards to Choose From<small>We are always adding more rewards.</small></h4>		
		<ul class="unstyled pad">
			<% @rewards.each do |reward| %>
				<li>
					<strong class="large">
						<div class="float-right">Points: <%= reward.points -%></div>
						<%= reward.name -%>
					</strong>
					<%= simple_format reward.description -%>
					<% if user_signed_in? && !admin_signed_in? %>
						<div class="dq-buttons">
							<% if reward.points <= (@user.lifetime_points - @user.used_points) %>
								<%= link_to 'Get This Reward', issue_reward_path(reward), data: { confirm: "By choosing okay you will use up #{reward.points} from your account. This can not be undone." }, :class => "lnk-button small" %>
							<% else %>
								<div class="lnk-button disable small">Not enough points.</div>
							<% end%>
						</div>
					<% end %>

					<% if admin_signed_in? %>
						<div class="dq-buttons">
							<%= link_to 'Edit Reward', edit_reward_path(reward) %>
						</div>
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>

	<div class="span4-12">
		<% if admin_signed_in? %>
			<h5>Admin Options</h5>
			<div class="dq-buttons pad-bottom">
				<%= link_to 'New Reward', new_reward_path, :class => "lnk-button full new" %>
			</div>
			
			<h5>Hidden Rewards</h5>
			<ul class="unstyled">
				<% @inactive_rewards.each do |reward| %>
					<li><strong><%= link_to reward.name, edit_reward_path(reward) -%></strong></li>
				<% end %>
			</ul>
		<% else %>
		<%= render 'shared/citizen' %>
		<% end %>
	</div>

</div>

app/views/rewards/index.mobile.erb
<% title "Rewards" %>
<!-- Standard Content -->
<div class="content">
	<div class="span12-12"><h3><i class="fa fa-trophy"></i> Player 1 Citizen<small>Your part of a special group.</small></h3></div>

	<% if @user.has_membership? %>
		<div class="span12-12 text-center"><h5>You have <u><%= @user.lifetime_points - @user.used_points -%></u> points available.</h5></div>
	<% end %>

	<div class="span12-12">
		<% unless admin_signed_in? %>
		<% if user_signed_in? && @user_rewards.size > 0 %>
			<h4>Your Rewards<small>These are the rewards you chose.</small></h4>		
			<ul class="unstyled lined pad">
				<% @user_rewards.each do |user_reward| %>
					<li style="clear: both; display: block;">
						<strong class="large">
							<div class="float-right">Code: <%= sprintf('%06d', user_reward.code) -%></div>
							<%= user_reward.reward.name -%>
						</strong>
						<div class="dq-buttons">
							<%= link_to "Use This Reward", user_redeem_url(user_reward.code, user_reward.user_id), :class => "lnk-button small full" -%>
						</div>
					</li>
				<% end %>
			</ul><br/>
		<% end %>
		<% end %>

		<h4>Rewards to Choose From<small>We are always adding more rewards.</small></h4>		
		<ul class="unstyled pad">
			<% @rewards.each do |reward| %>
				<li style="clear: both; display: block;" class="pad-bottom">
					<strong class="large">
						<div class="float-right">Points: <%= reward.points -%></div>
						<%= reward.name -%>
					</strong>
					<%= simple_format reward.description -%>
					<% if user_signed_in? && !admin_signed_in? %>
						<div class="dq-buttons">
							<% if reward.points <= (@user.lifetime_points - @user.used_points) %>
								<%= link_to 'Get This Reward', issue_reward_path(reward), data: { confirm: "By choosing okay you will use up #{reward.points} from your account. This can not be undone." }, :class => "lnk-button small full" %>
							<% else %>
								<div class="lnk-button full disable small">Not enough points.</div>
							<% end%>
						</div>
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/rewards/new.html.erb
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-pencil"></i> Create Reward <small>Filling out forms are great.</small></h2></div>
	<div class="span8-12">
		<%= render 'form' %>
	</div>

	<div class="span4-12">
		<h5>Admin Options</h5>
		<div class="dq-buttons">
			<%= link_to 'Go Back to Rewards', play_path, :class => "lnk-button full back" %>
		</div>
	</div>
</div>

app/views/rewards/redeem.html.erb
<div class="content">
	<div class="span12-12"><h4><i class="fa fa-barcode"></i> Code Redeem <small>For redemption of discounts.</small></h4></div>
	<div class="span12-12">

		<%= form_tag post_redeem_reward_path do |f| %>
			<div class="dq-form">
				<div class="field10-10"><%= telephone_field_tag :code, nil, :placeholder => "Redemption Code", :autofocus => true, :maxlength => 6 %></div>
				<div class="dq-buttons">
					<%= submit_tag "Use Reward", :class => "full" %>
				</div>
			</div>

		<% end %>

	</div>

	<div class="span12-12"><h4><i class="fa fa-barcode"></i> Citizen Checkin <small>Disable for the day.</small></h4></div>
	<div class="span12-12">

		<%= form_tag post_citizen_checkin_reward_path do |f| %>
			<div class="dq-form">
				<div class="field10-10"><%= telephone_field_tag :code, nil, :placeholder => "Citizen Code", :autofocus => false, :maxlength => 8 %></div>
				<div class="dq-buttons">
					<%= submit_tag "Check In", :class => "full" %>
				</div>
			</div>

		<% end %>

	</div>
</div>

app/views/rewards/redeem.mobile.erb
<div class="content">
	<div class="span12-12"><h4><i class="fa fa-barcode"></i> Code Redeem <small>For redemption of discounts.</small></h4></div>
	<div class="span12-12">

		<%= form_tag post_redeem_reward_path do |f| %>
			<div class="dq-form">
				<div class="field10-10"><%= telephone_field_tag :code, nil, :placeholder => "Redemption Code", :autofocus => true, :maxlength => 6 %></div>
				<div class="dq-buttons">
					<%= submit_tag "Use Reward", :class => "full" %>
				</div>
			</div>

		<% end %>

	</div>

	<div class="span12-12"><h4><i class="fa fa-barcode"></i> Citizen Checkin <small>Disable for the day.</small></h4></div>
	<div class="span12-12">

		<%= form_tag post_citizen_checkin_reward_path do |f| %>
			<div class="dq-form">
				<div class="field10-10"><%= telephone_field_tag :code, nil, :placeholder => "Citizen Code", :autofocus => false, :maxlength => 8 %></div>
				<div class="dq-buttons">
					<%= submit_tag "Check In", :class => "full" %>
				</div>
			</div>

		<% end %>

	</div>
</div>

app/views/rewards/user_redeem.html.erb
<% title "Rewards" %>
<!-- Standard Content -->
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-trophy"></i> Reward<small>Your part of a special group.</small></h2></div>
	<div class="span12-12">
		<h4><%= @discount.reward.name -%></h4>
		<%= simple_format @discount.reward.description, :class => "small" -%>
		<p class="small"><strong>Reward Code</strong>: <%= @discount.code -%></p>
		
		<%= form_tag post_user_redeem_reward_path do |f| %>
			<%= hidden_field_tag :code, @discount.code %>
			<%= hidden_field_tag :user_id, @discount.user_id %>
			<%= hidden_field_tag :from_user, true %>
			<div class="dq-buttons">
				<%= submit_tag "Game Master Button", data: { confirm: "The Player 1 staff should be the one who hit this button for you to use this or else you lose this reward FOREVER!" }, :class => "full" %>
			</div>
		<% end %>
		
	</div>
</div>

app/views/rewards/user_redeem.mobile.erb
<% title "Rewards" %>
<!-- Standard Content -->
<div class="content">
	<div class="span12-12"><h3><i class="fa fa-trophy"></i> Reward<small>Your part of a special group.</small></h3></div>
	<div class="span12-12">
		<h4><%= @discount.reward.name -%></h4>
		<%= simple_format @discount.reward.description, :class => "small" -%>
		<p class="small"><strong>Reward Code</strong>: <%= @discount.code -%></p>
		
		<%= form_tag post_user_redeem_reward_path do |f| %>
			<%= hidden_field_tag :code, @discount.code %>
			<%= hidden_field_tag :user_id, @discount.user_id %>
			<%= hidden_field_tag :from_user, true %>
			<div class="dq-buttons">
				<%= submit_tag "Game Master Button", data: { confirm: "The Player 1 staff should be the one who hit this button for you to use this or else you lose this reward FOREVER!" }, :class => "full" %>
			</div>
		<% end %>
		
	</div>
</div>