config/routes.rb
Player1orlando::Application.routes.draw do
  
  devise_for :admins
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  
  get '/rewards/redemption', to: 'rewards#redeem', as: 'redeem_reward'
  get '/vip/checkin/process', to: 'pages#process_vip_checkin', as: 'process_vip_checkin'
  post '/rewards/redeem', to: 'rewards#post_redeem', as: 'post_redeem_reward'
  post '/rewards/post_user_redeem', to: 'rewards#post_user_redeem', as: 'post_user_redeem_reward'
  post '/citizen/checkin/process', to: 'rewards#post_citizen_checkin', as: 'post_citizen_checkin_reward'
  post '/membership/process', to: 'pages#process_memberships', as: 'process_memberships'
  
  get '/rate/drink/:id/:rating', to: 'ratings#set_rating', as: 'set_rating'
  get '/rate/game/:id/:rating', to: 'ratings#set_game_rating', as: 'set_game_rating'
  get '/rewards/issue/:id', to: 'rewards#issue', as: 'issue_reward'
  get '/d/:code/:user_id', to: 'rewards#user_redeem', as: 'user_redeem'
  
  get '/beverages/', to: 'categories#index', as: 'beverages', :defaults => { :area => 'drinks' }

  get '/beverages/dispense/:dispense_type', to: 'beverages#show_by_dispense_type', as: 'dispense_beverages'
  get '/beverages/updates/:update_style', to: 'beverages#show_by_update_style', as: 'update_beverages'
  get '/beverages/printable/:dispense_type', to: 'beverages#show_by_printable', as: 'printable_beverages'
  get '/beverages/printable/:dispense_type/:dispense_type2', to: 'beverages#show_by_printable', as: 'printable_beverages2'
  get '/beverages/printable/:dispense_type/:dispense_type2/:dispense_type3', to: 'beverages#show_by_printable', as: 'printable_beverages3'
  get '/beverages/printable_custom/:view_options', to: 'beverages#show_by_printable_custom', as: 'printable_custom'

  get '/beverages/hidden', to: 'categories#allhidden', as: 'hidden_beverages', :defaults => { :area => 'drinks' }
  get '/play/', to: 'categories#index', as: 'play', :defaults => { :area => 'games' }
  get '/play/hidden', to: 'categories#allhidden', as: 'hidden_play', :defaults => { :area => 'games' }
  
  get '/manual/info', to: 'pages#info', as: 'infos_page'
  get '/manual/vips', to: 'pages#vips', as: 'vips_page'
  get '/manual/citizens', to: 'pages#rewards', as: 'rewards_page'
  get '/manual/rules', to: 'pages#rules', as: 'rules_page'
  get '/manual/terms', to: 'pages#terms', as: 'terms_page'
  get '/manual/privacy', to: 'pages#privacy', as: 'privacy_page'
  get '/feed', to: 'pages#feed', as: 'feed_rss'
  get '/happyhour', to: 'pages#happyhour', as: 'happy_hour_page'
  get '/food', to: 'pages#food', as: 'food_page'
  get '/music', to: 'pages#music', as: 'music_page'
  get '/bartender_choice', to: 'pages#bartender_choice', as: 'bartender_choice_page'
  get '/leaderboard', to: 'pages#leaderboard', as: 'leaderboard_page'

  get '/tvboards/draft', to: 'taps#tvboard', as: 'tvboard_draft_page'
  get '/tvboards_hor/draft', to: 'taps#tvboard_hor', as: 'tvboard_hor_draft_page'
  get '/tvboards/bottle/:id', to: 'drinks#tvscreen', as: 'tvboard_bottle_page'

  get '/drinks/all/edit', to: 'drinks#edit_all', as: 'edit_all_drinks'
  put '/drinks/all', to: 'drinks#update_all', as: 'update_all_drinks'

  
  resources :users, :only => [:show, :index, :edit, :update, :destroy]
  resources :katy_corners, :path => "katys"
  resources :trackers, :path => "drink_tracker" do
    member do
      get 'track'
      post 'point_track'
    end
  end
  resources :categories, :beer_styles, :drinks, :games, :events, :galleries
  resources :taps
  
  
  get '/citizen/checkin', to: 'pages#citizen_checkin', as: 'citizen_checkin'
  resources :rewards, :path => "citizen" do
    member do
      # get 'redeem'
      # post 'post_redeem'
      # post 'post_citizen_checkin'
    end
  end

  
  
  root 'pages#index'
end

app/views/shared/_activity.html.erb
<h4>Your Activity<small>You've been busy!</small></h4>
<ul class="unstyled lined">
	<% @user.timelines.order(created_at: :desc).page.each do |timeline| %>
		<% if timeline.nature.downcase == "create" %>
			<li><%= @user.first_name.capitalize -%> created their account with Player 1 on <%= timeline.created_at.to_s(:quick_date) -%>. We called them <strong>awesome</strong> that day!</li>
		<% elsif timeline.nature.downcase == "drink" %>
			<li>Just had a good drink of <%= link_to timeline.drink.name, drink_path(timeline.drink) -%> at  <%= timeline.created_at.to_s(:quick_date) -%>.</li>
		<% elsif timeline.nature.downcase == "drink_rate" %>
			<li>Rated the drink <%= link_to timeline.drink.name, drink_path(timeline.drink) -%> a <%= @user.ratings.where(:drink_id => timeline.drink).first.rating -%> out of 5 at <%= timeline.created_at.to_s(:quick_date) -%>.</li>
		<% elsif timeline.nature.downcase == "game_rate" %>
			<li>Rated the game <%= link_to timeline.game.name, game_path(timeline.game) -%> a <%= @user.ratings.where(:drink_id => timeline.drink).first.rating -%> out of 5 at <%= timeline.created_at.to_s(:quick_date) -%>.</li>
		<% elsif timeline.nature.downcase == "checkin" %>
			<li><%= @user.first_name.capitalize -%> checked in at Player 1 on <%= timeline.created_at.to_s(:quick_date) -%>.</li>
		<% else %>
			<li>On <%= timeline.created_at.to_s(:quick_date) -%> they <%= timeline.nature -%>.</li>
		<% end %>
	<% end %>
</ul>

app/views/shared/_activity2.html.erb
<h4>Your Activity<small>You've been busy!</small></h4>
<ul class="unstyled lined">
	<% @user.timelines.order(created_at: :desc).page.each do |timeline| %>
		<% if timeline.nature.downcase == "create" %>
			<li><%= @user.first_name.capitalize -%> created his account with Player 1 on <%= timeline.created_at.to_s(:quick_date) -%>. We called him <strong>awesome</strong> that day!</li>
		<% elsif timeline.nature.downcase == "drink" %>
			<li>Just had a good drink of <%= link_to timeline.drink.name, drink_path(timeline.drink) -%> at  <%= timeline.created_at.to_s(:quick_date) -%>.</li>
		<% elsif timeline.nature.downcase == "drink_rate" %>
			<li>Rated the drink <%= link_to timeline.drink.name, drink_path(timeline.drink) -%> a <%= @user.ratings.where(:drink_id => timeline.drink).first.rating -%> out of 5 at <%= timeline.created_at.to_s(:quick_date) -%>.</li>
		<% elsif timeline.nature.downcase == "game_rate" %>
			<li>Rated the game <%= link_to timeline.game.name, game_path(timeline.game) -%> a <%= @user.ratings.where(:drink_id => timeline.drink).first.rating -%> out of 5 at <%= timeline.created_at.to_s(:quick_date) -%>.</li>
		<% else %>
			<li>On <%= timeline.created_at.to_s(:quick_date) -%> they <%= timeline.nature -%>.</li>
		<% end %>
	<% end %>
</ul>

app/views/shared/_citizen.html.erb
<% if !@user.membership_number.blank? %>
	<% unless admin_signed_in? %>
		<div class="callout_box">
			<h5>Player 1 VIP Membership</h5>
			<ul class="unstyled lined">
				<li class="large"><span class="float-right"><%= @user.vip_membership_points  -%></span><strong>Total Points</strong></li>
			</ul>
			<div class="dq-buttons">
				<span class="lnk-button small secondary">Updated Weekly</span>
				<%= link_to "See levels", vips_page_path, :class => "lnk-button small" %>
			</div>
		</div>
	<% end %>
<% elsif @user.has_membership? %>
	<% unless admin_signed_in? %>
		<!-- <div class="callout_box">
			<h5>Player 1 Citizen</h5>
			<ul class="unstyled lined">
				<li class="large"><span class="float-right"><%= @user.lifetime_points - @user.used_points -%></span><strong>Available Points</strong></li>
				<li><span class="float-right"><%= @user.used_points -%></span><strong>Used Points</strong></li>
				<li><span class="float-right"><%= @user.lifetime_points -%></span><strong>Lifetime Points</strong></li>
			</ul>
			<div class="dq-buttons">
				<%= link_to "How it all works?", rewards_page_path, :class => "lnk-button small secondary" %>
				<%= link_to "Available Rewards", rewards_path, :class => "lnk-button small" %>
			</div>
		</div> -->
	<% end %>
<% else %>
	<!-- <div class="callout_box">
		<h5>Become a Player 1 Citizen.</h5>
		<p>Becoming a citizen allows you to earn points towards free covers for friends, swag, discounts, and more! Just ask you game master at the front of Player 1 for more details. Remember one of the limitations is you can't earn points on Fridays and Saturdays.</p>
	</div> -->
<% end %>

app/views/shared/_drink_search_form.html.erb
<h5>Search Drinks</h5>

<%= form_tag drinks_path, method: :get do %>
<div class="dq-form pad-bottom">
	<div class="field10-10"><%= text_field_tag :query, params[:query], :placeholder => "Search for a Drink" %></div>
	<div class="dq-buttons">
		<%= link_to "Tap List", taps_path, :class => "lnk-button grey" %>
		<%= submit_tag "Search Drinks", name: nil %>
	</div>
</div>
<% end %>

app/views/shared/_drink_search_form.mobile.erb
<%= form_tag drinks_path, method: :get do %>
<div class="dq-form">
	<div class="field10-10"><%= text_field_tag :query, params[:query], :placeholder => "Search for a Drink" %></div>
	<div class="dq-buttons">
		<%= link_to 'Tap List', taps_path, :class => "lnk-button" %>
		<button>Search Drinks</button>
	</div>
</div>
<% end %>

app/views/shared/_game_search_form.html.erb
<h5>Search Games</h5>

<%= form_tag games_path, method: :get do %>
<div class="dq-form pad-bottom">
	<div class="field10-10"><%= text_field_tag :query, params[:query], :placeholder => "Search for a Game" %></div>
	<div class="dq-buttons">
		<%= submit_tag "Search Game", name: nil %>
	</div>
</div>
<% end %>

app/views/shared/_game_search_form.mobile.erb
<h5>Search Games</h5>

<%= form_tag games_path, method: :get do %>
<div class="dq-form">
	<div class="field10-10"><%= text_field_tag :query, params[:query], :placeholder => "Search for a Game" %></div>
	<div class="dq-buttons">
		<%= link_to 'Categories', play_path, :class => "lnk-button" %>
		<button>Search Games</button>
	</div>
</div>
<% end %>

app/views/shared/_social.html.erb
<div class="text-right">
	<div class="g-plusone" data-size="medium" data-annotation="none" data-href="<%= url_pass -%>"></div>
	<a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= url_pass -%>" data-text="Player 1's got <%= title_page -%>" data-via="player1orlando" data-related="player1orlando" data-count="none">Tweet</a>
	<div class="fb-like" data-href="<%= url_pass -%>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
</div>

app/views/shared/_social.mobile.erb
<div class="text-right">
	<div class="g-plusone" data-size="medium" data-annotation="none" data-href="<%= url_pass -%>"></div>
	<a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= url_pass -%>" data-text="Player 1's got <%= title_page -%>" data-via="player1orlando" data-related="player1orlando" data-count="none">Tweet</a>
	<div class="fb-like" data-href="<%= url_pass -%>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
</div>

app/views/shared/_user_search_form.html.erb
<h5>Search Users</h5>

<%= form_tag users_path, method: :get do %>
<div class="dq-form pad-bottom">
	<div class="field10-10"><%= text_field_tag :query, params[:query], :placeholder => "Search for a User" %></div>
	<div class="dq-buttons">
		<%= submit_tag "Search Users", name: nil, :class => "full" %>
	</div>
</div>
<% end %>

app/views/shared/_wannaplay.html.erb
<h5>Want to play one?</h5>
<p>All games you see listed here are available to play on one of our consoles in the gaming lounge. To play a game just see the Game Master at the front of Player 1. Remember to check out a game/controller you must have an open tab at the bar and have at least two drinks per hour on your tab.</p>

app/views/shared/_whycraft.html.erb
<h5>Want to take a bottle home?</h5>
<p>Player 1 now has a To-Go option for those on the run or wanting to continue the party at home! Order by phone or with our lovely game tenders located in the front of the bar! You can order as few as one beer, or as many as you want, create your own six pack, we've got you covered! All to-go orders will receive an additional 10% off their entire order!As an added bonus, Members who have reached new levels in our membership program will use their discount perks instead!</p>
<p>Call 407.778.4815 to order a bottle and come pick it up.</p>

<h5>Why only craft beers?</h5>
<p>The number one reason is <strong>craft beer tastes better</strong> than the "beer water" that is mass produced and mass marketed by the big beer companies. Craft beer tastes better because craft brewers spend their time focusing the quality of their beer rather than focusing on their marketing campaigns and stock prices.</p>
<p>Oh yeah! Craft beers can pack a punch. Most craft beers range from 5-10% ABV, but some can reach 20%, 30%, and even 40% ABV.</p>
<div class="dq-buttons pad-bottom">
	<%= link_to 'Beer Styles', beer_styles_path, :class => "lnk-button full" %>
</div>