config/routes.rb
Player1orlando::Application.routes.draw do
  
  devise_for :admins
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  
  get '/rewards/redemption', to: 'rewards#redeem', as: 'redeem_reward'
  get '/vip/checkin/process', to: 'pages#process_vip_checkin', as: 'process_vip_checkin'
  post '/rewards/redeem', to: 'rewards#post_redeem', as: 'post_redeem_reward'
  post '/rewards/post_user_redeem', to: 'rewards#post_user_redeem', as: 'post_user_redeem_reward'
  post '/citizen/checkin/process', to: 'rewards#post_citizen_checkin', as: 'post_citizen_checkin_reward'
  post '/membership/process', to: 'pages#process_memberships', as: 'process_memberships'
  
  get '/rate/drink/:id/:rating', to: 'ratings#set_rating', as: 'set_rating'
  get '/rate/game/:id/:rating', to: 'ratings#set_game_rating', as: 'set_game_rating'
  get '/rewards/issue/:id', to: 'rewards#issue', as: 'issue_reward'
  get '/d/:code/:user_id', to: 'rewards#user_redeem', as: 'user_redeem'
  
  get '/beverages/', to: 'categories#index', as: 'beverages', :defaults => { :area => 'drinks' }

  get '/beverages/dispense/:dispense_type', to: 'beverages#show_by_dispense_type', as: 'dispense_beverages'
  get '/beverages/updates/:update_style', to: 'beverages#show_by_update_style', as: 'update_beverages'
  get '/beverages/printable/:dispense_type', to: 'beverages#show_by_printable', as: 'printable_beverages'
  get '/beverages/printable/:dispense_type/:dispense_type2', to: 'beverages#show_by_printable', as: 'printable_beverages2'
  get '/beverages/printable/:dispense_type/:dispense_type2/:dispense_type3', to: 'beverages#show_by_printable', as: 'printable_beverages3'
  get '/beverages/printable_custom/:view_options', to: 'beverages#show_by_printable_custom', as: 'printable_custom'

  get '/beverages/hidden', to: 'categories#allhidden', as: 'hidden_beverages', :defaults => { :area => 'drinks' }
  get '/play/', to: 'categories#index', as: 'play', :defaults => { :area => 'games' }
  get '/play/hidden', to: 'categories#allhidden', as: 'hidden_play', :defaults => { :area => 'games' }
  
  get '/manual/info', to: 'pages#info', as: 'infos_page'
  get '/manual/vips', to: 'pages#vips', as: 'vips_page'
  get '/manual/citizens', to: 'pages#rewards', as: 'rewards_page'
  get '/manual/rules', to: 'pages#rules', as: 'rules_page'
  get '/manual/terms', to: 'pages#terms', as: 'terms_page'
  get '/manual/privacy', to: 'pages#privacy', as: 'privacy_page'
  get '/feed', to: 'pages#feed', as: 'feed_rss'
  get '/happyhour', to: 'pages#happyhour', as: 'happy_hour_page'
  get '/food', to: 'pages#food', as: 'food_page'
  get '/music', to: 'pages#music', as: 'music_page'
  get '/bartender_choice', to: 'pages#bartender_choice', as: 'bartender_choice_page'
  get '/leaderboard', to: 'pages#leaderboard', as: 'leaderboard_page'

  get '/tvboards/draft', to: 'taps#tvboard', as: 'tvboard_draft_page'
  get '/tvboards_hor/draft', to: 'taps#tvboard_hor', as: 'tvboard_hor_draft_page'
  get '/tvboards/bottle/:id', to: 'drinks#tvscreen', as: 'tvboard_bottle_page'

  get '/drinks/all/edit', to: 'drinks#edit_all', as: 'edit_all_drinks'
  put '/drinks/all', to: 'drinks#update_all', as: 'update_all_drinks'

  
  resources :users, :only => [:show, :index, :edit, :update, :destroy]
  resources :katy_corners, :path => "katys"
  resources :trackers, :path => "drink_tracker" do
    member do
      get 'track'
      post 'point_track'
    end
  end
  resources :categories, :beer_styles, :drinks, :games, :events, :galleries
  resources :taps
  
  
  get '/citizen/checkin', to: 'pages#citizen_checkin', as: 'citizen_checkin'
  resources :rewards, :path => "citizen" do
    member do
      # get 'redeem'
      # post 'post_redeem'
      # post 'post_citizen_checkin'
    end
  end

  
  
  root 'pages#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :drinks, dependent: :destroy
  has_many :games, dependent: :destroy
  
  validates :name, :description, :area, presence: true
  

  def to_param
    [id, name.parameterize].join("-")
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy, :allhidden]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @cat_type = params[:area]
    
    if params[:area] == "drinks"
      @drink_dispense_styles = Drink::DISPENSE_TYPE
      @drink_update_styles = Drink::UPDATE_STYLES.invert.except!("4").invert
    end
    
    @categories = Category.where(:area => params[:area]).order(order: :asc, name: :asc)
    if admin_signed_in?
      if @cat_type == "drinks"
        @all_hidden = Drink.where(:visible => false).order(name: :asc).limit(10)
      else
        @all_hidden = Game.where(:visible => false).order(name: :asc).limit(10)
      end
    end
  end

  def allhidden
    @cat_type = params[:area]
    if admin_signed_in?
      if @cat_type == "drinks"
        if params[:call_out].to_s == "true"
          @all_hidden = Drink.where(:call_out => true).where(:visible => true).order(name: :asc)
        elsif params[:tracker].to_s == "true"
          @all_hidden = Drink.where(:tracker => true).where(:visible => true).order(name: :asc)
        else
          @all_hidden = Drink.where(:visible => false).order(name: :asc)
        end
      else
        @all_hidden = Game.where(:visible => false).order(name: :asc)
      end
    end
  end

  def show
    if admin_signed_in?
      if @cat_type == "drinks"
        @all_hidden = Drink.where(:visible => false).order(name: :asc).limit(10)
      else
        @all_hidden = Game.where(:visible => false).order(name: :asc).limit(10)
      end
    end
  end
  
  def new
    @category = Category.new(:area => params[:area], :visible => true)
  end
  
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_path(@category), notice: 'Category was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_path(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end
  
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
    end
  end
  
  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :visible, :order, :area)
    end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/allhidden.html.erb
<!-- Standard Content -->
<div class="content">
	<% if @cat_type == "drinks" %>
		<% title "Drinks" %>
		<div class="span12-12"><h2><i class="fa fa-beer"></i> Drinks<small>Gaming without poitions...wrong.</small></h2></div>
	<% elsif @cat_type == "games" %>
		<% title "Games" %>
		<div class="span12-12"><h2><i class="fa fa-gamepad"></i> Games<small>Achievement Unlocked!</small></h2></div>
	<% end %>

	<div class="span8-12">
        <% if params[:call_out].to_s == "true" %>
			<h4>Called Out Items<small>These appear on the homepage.</small></h4>
        <% elsif params[:tracker].to_s == "true" %>
			<h4>Tracker Items<small>These appear on the larger on the drink tracker.</small></h4>
		<% else %>
			<h4>Hidden Items<small>Don't worry it's not the end of the world.</small></h4>
		<% end %>
		
		<ul class="unstyled lined">
			<% if @cat_type == "drinks" %>
				<% @all_hidden.each do |drink| %>
					<li><div class="float-right">In <%= drink.quick_style -%></div> <strong><%= link_to drink.name, edit_drink_path(drink) -%></strong></li>
				<% end %>
			<% elsif @cat_type == "games" %>
				<% @all_hidden.each do |game| %>
					<li><div class="float-right">In <%= game.category.name -%></div> <strong><%= link_to game.name, edit_game_path(game) -%></strong></li>
				<% end %>
			<% end %>
		</ul>
	</div>

	<div class="span4-12">
		<% if @cat_type == "drinks" %>
			<% if admin_signed_in? %>
				<h5>Admin Options</h5>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'Back', beverages_path, :class => "lnk-button full new" %>
					<%= params[:call_out] %>
				</div>
			<% else %>
				<%= render 'shared/whycraft' %>
			<% end %>
		<% elsif @cat_type == "games" %>
			<% if admin_signed_in? %>
				<h5>Admin Options</h5>
				<div class="dq-buttons">
					<%= link_to 'Back', play_path, :class => "lnk-button full new" %>
				</div>
			<% else %>
				<%= render 'shared/wannaplay' %>
				<h5>Coin Op Classics</h5>
				<p>An ever-changing selection of classic arcade and pinball machines surround the bar, showcasing the best from the coin-op era of gaming with no need for any coins, play as much as you like.</p>
				<h5>And of course</h5>
				<p>Atari 2600/5200, Colecovision, NES, Sega Genesis, SNES, Nintendo64, Sega Saturn, Playstation 1, Sega Dreamcast, PS2, PS3, X360, and PC. But who's counting.</p>
			<% end %>
		<% end %>
	</div>
</div>

</div>

app/views/categories/index.html.erb
<!-- Standard Content -->
<div class="content">
	<% if @cat_type == "drinks" %>
		<% title "Drinks" %>
		<div class="span12-12"><h2><i class="fa fa-beer"></i> Drinks<small>Gaming without poitions...wrong.</small></h2></div>
	<% elsif @cat_type == "games" %>
		<% title "Games" %>
		<div class="span12-12"><h2><i class="fa fa-gamepad"></i> Games<small>Achievement Unlocked!</small></h2></div>
	<% end %>

	<div class="span8-12">
		<h4>Choose a menu item<small>Don't worry it's not the end of the world.</small></h4>
		
		<% if @cat_type == "drinks" %>
			<%= render 'shared/drink_search_form' %>

			
			<ul class="unstyled pad">
				<li><strong class="large"><%= link_to "View by Beer Style", beer_styles_path -%></strong></li>

				<% @drink_update_styles.each do |name, value| %>
					<li><strong class="large"><%= link_to name, update_beverages_path(:update_style => value) -%></strong></li>
				<% end %>

				<% @drink_dispense_styles.each do |name, value| %>
					<li><strong class="large"><%= link_to name, dispense_beverages_path(:dispense_type => value) -%></strong><% if admin_signed_in? %> <%= link_to "[Printable]", printable_beverages_path(:dispense_type => value) -%><% end %></li>
				<% end %>
			</ul>

		<% elsif @cat_type == "games" %>
			<%= render 'shared/game_search_form' %>

			<ul class="unstyled">
				<% @categories.where(:visible => true).each do |category| %>
					<li><strong class="large"><%= link_to category.name, category_path(category) -%></strong><p class="small"><%= category.description -%></p></li>
				<% end %>
			</ul>
		<% end %>
		
	</div>

	<div class="span4-12">
		<% if @cat_type == "drinks" %>
			<% if admin_signed_in? %>
				<h5>Admin Options</h5>
				<div class="dq-buttons pad-bottom">
					<!-- <%= link_to 'New Drink Category', new_category_path(:area => "drinks"), :class => "lnk-button full new" %> -->
					<%= link_to 'Show Call Out Drinks', hidden_beverages_path(:call_out => true), :class => "lnk-button full" %>
					<%= link_to 'Show Tracker Drinks', hidden_beverages_path(:tracker => true), :class => "lnk-button full" %>
					<%= link_to 'Edit All Drinks', edit_all_drinks_path, :class => "lnk-button full" %>
					
					<% @drink_dispense_styles.each do |name, value| %>
						<%= link_to "Edit #{name} Drinks", edit_all_drinks_path(:limit => value), :class => "lnk-button full" %>
					<% end %>
					
					
					<%= link_to 'See All Hidden Items', hidden_beverages_path, :class => "lnk-button full" %>
				</div>
				
				<!-- <h5>Hidden Categories</h5>
				<ul class="unstyled">
					<% @categories.where(:visible => false).each do |category| %>
						<li><strong><%= link_to category.name, category_path(category) -%></strong></li>
					<% end %>
				</ul> -->

				<h5>Create Printable Links</h5>
					<p>One section is /beverages/printable/KEY</p>
					<p>Two sections is /beverages/printable/KEY/KEY</p>
					<p>Three sections is /beverages/printable/KEY/KEY/KEY</p>
					<p>To make font small add "?smallfont=true" to the end of the URL</p>
					
				<ul>
					
					<li><strong>Available Keys</strong></li>
					<% @drink_dispense_styles.each do |name, value| %>
						<li><%= value -%></li>
					<% end %>
				</ul>
				<!-- <ul class="unstyled lined">
					<% @all_hidden.each do |drink| %>
						<li><strong><%= link_to drink.name, edit_drink_path(drink) -%></strong><br/>In <%= drink.category.name -%></li>
					<% end %>
				</ul> -->
				<!-- <div class="text-right"><%= link_to "See All Hidden Items", hidden_beverages_path %></div> -->
			<% else %>
				<% if user_signed_in? %>
				<h5>Not Tried Yet</h5>
				<% random_drinks = find_random_drinks(current_user, 3)%>
				<ul class="unstyled pad">
					<% random_drinks.each do |drink| %>
						<li><strong class="large"><div class="thumbnail-image"><%= image_tag drink.drink_image.thumb -%></div> <%= link_to drink.name, drink_path(drink) -%></strong><%= simple_format drink.description -%></li>
					<% end %>
				</ul>
				<% end %>
				
				<%= render 'shared/whycraft' %>
			<% end %>
		<% elsif @cat_type == "games" %>
			<% if admin_signed_in? %>
				<h5>Admin Options</h5>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'New Games Category', new_category_path(:area => "games"), :class => "lnk-button full new" %>
				</div>

				<h5>Hidden Categories</h5>
				<ul class="unstyled">
					<% @categories.where(:visible => false).each do |category| %>
						<li><strong><%= link_to category.name, category_path(category) -%></strong></li>
					<% end %>
				</ul>

				<h5>All Hidden Games</h5>
				<ul class="unstyled lined">
					<% @all_hidden.each do |game| %>
						<li><strong><%= link_to game.name, edit_game_path(game) -%></strong><br/>In <%= game.category.name -%></li>
					<% end %>
				</ul>
				<div class="text-right"><%= link_to "See All Hidden Items", hidden_play_path %></div>
			<% else %>
				<%= render 'shared/wannaplay' %>
				<h5>Coin Op Classics</h5>
				<p>An ever-changing selection of classic arcade and pinball machines surround the bar, showcasing the best from the coin-op era of gaming with no need for any coins, play as much as you like.</p>
				<h5>And of course</h5>
				<p>Atari 2600/5200, Colecovision, NES, Sega Genesis, SNES, Nintendo64, Sega Saturn, Playstation 1, Sega Dreamcast, PS2, PS3, X360, and PC. But who's counting.</p>
			<% end %>
		<% end %>
	</div>
</div>

</div>

app/views/categories/index.mobile.erb
<!-- Standard Content -->
<div class="content">
	<% if @cat_type == "drinks" %>
		<% title "Drinks" %>
		<div class="span12-12"><h3><i class="fa fa-beer"></i> Drinks<small>Gaming without poitions...wrong.</small></h3></div>
	<% elsif @cat_type == "games" %>
		<% title "Games" %>
		<div class="span12-12"><h3><i class="fa fa-gamepad"></i> Games<small>Achievement Unlocked!</small></h3></div>
	<% end %>

	<div class="span12-12">
		<h4>Choose a menu item<small>Don't worry it's not the end of the world.</small></h4>
		
		<% if @cat_type == "drinks" %>
			<%= render 'shared/drink_search_form' %>

			<ul class="unstyled pad pad-top">
				<li><strong class="large"><%= link_to "View by Beer Style", beer_styles_path -%></strong></li>
				
				<% @drink_update_styles.each do |name, value| %>
					<li><strong class="large"><%= link_to name, update_beverages_path(:update_style => value) -%></strong></li>
				<% end %>

				<% @drink_dispense_styles.each do |name, value| %>
					<li><strong class="large"><%= link_to name, dispense_beverages_path(:dispense_type => value) -%></strong></li>
				<% end %>
			</ul>
		<% elsif @cat_type == "games" %>
			<%= render 'shared/game_search_form' %>
			<ul class="unstyled pad-top">
				<% @categories.where(:visible => true).each do |category| %>
					<li><strong class="large"><%= link_to category.name, category_path(category) -%></strong><p class="small"><%= category.description -%></p></li>
				<% end %>
			</ul>
		<% end %>
		
	</div>

</div>

app/views/categories/show.html.erb
<% title @category.name %>

<!-- Standard Content -->
<div class="content">
	<% if @category.area == "drinks" %>
		<div class="span12-12"><h2><i class="fa fa-beer"></i> Drinks<small>Gaming without poitions...wrong.</small></h2></div>
	<% elsif @category.area == "games" %>
		<div class="span12-12"><h2><i class="fa fa-gamepad"></i> Games<small>Achievement Unlocked!</small></h2></div>
	<% end %>
	
	<div class="span8-12">
		<h4><%= @category.name -%><small><%= @category.description -%></small></h4>
		
		<ul class="unstyled">
			<% if @category.area == "drinks" %>
				<% @category.drinks.where(:visible => true).order(name: :asc).each do |drink| %>
					<% if drink.call_out? %>
					<li class="callout_box">
					<% else %>
					<li>
					<% end %>
						<strong class="large"><div class="thumbnail-image"><%= image_tag drink.drink_image.thumb -%></div>  <%= link_to drink.name, drink_path(drink) -%><div class="small"><%= drink.brewery -%></div></strong><%= simple_format drink.description -%>
						<% if admin_signed_in? -%><div class="text-right">Image: <%= drink.drink_image? -%> | Average Rating: <%= raw star_view drink.average_rating -%> | <%= link_to 'Edit', edit_drink_path(drink) %> | <%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></div><% end -%>
					</li>
				<% end %>
			<% elsif @category.area == "games" %>
				<% @category.games.where(:visible => true).order(name: :asc).each do |game| %>
					<li>
						<strong class="large"><div class="thumbnail-image"><%= image_tag game.cover_art.thumb -%></div>  <%= link_to game.name, game_path(game) -%></strong><%= simple_format truncate game.description, length: 128 -%>
						<% if admin_signed_in? -%><div class="text-right">Image: <%= game.cover_art? -%> | <%= link_to 'Edit', edit_game_path(game) %> | <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></div><% end -%>
					</li>
				<% end %>
			<% end %>
		</ul>
	</div>
	
	<div class="span4-12">
		<% if @category.area == "drinks" %>
			<%= render 'shared/drink_search_form' %>
			<% if admin_signed_in? %>
				<h5>Admin Options</h5>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'Go Back to Categories', beverages_path, :class => "lnk-button full back" %>

					<%= link_to 'Add New Drink to this Category', new_drink_path(:category_id => @category.id), :class => "lnk-button full pad-space new" %>

					<%= link_to 'Edit Drink Category', edit_category_path(@category), :class => "lnk-button full edit" %>
					<%= link_to 'Destroy Drink Category', @category, method: :delete, data: { confirm: 'Are you sure? This will destory all items under this category as well. It is recommended to just change the visibilty of the category.' }, :class => "lnk-button full cancel delete" %>
				</div>
				<h5>Hidden Drinks</h5>
				<ul class="unstyled lined">
					<% @category.drinks.where(:visible => false).each do |drink| %>
						<li><strong><%= link_to drink.name, edit_drink_path(drink) -%></strong></li>
					<% end %>
				</ul>
				
				<h5>All Hidden Drinks</h5>
				<ul class="unstyled lined">
					<% @all_hidden.each do |drink| %>
						<li><strong><%= link_to drink.name, edit_drink_path(drink) -%></strong><br/>In <%= drink.category.name -%></li>
					<% end %>
				</ul>
				<div class="text-right"><%= link_to "See All Hidden Items", hidden_beverages_path %></div>
			<% else %>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'Go Back', beverages_path, :class => "lnk-button full" %>
				</div>
				<%= render 'shared/whycraft' %>
			<% end %>
		<% elsif @category.area == "games" %>
			<%= render 'shared/game_search_form' %>
			<% if admin_signed_in? %>
				<h5>Admin Options</h5>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'Go Back to Categories', play_path, :class => "lnk-button full" %>

					<%= link_to 'Add New Game to this Category', new_game_path(:category_id => @category.id), :class => "lnk-button full pad-space" %>

					<%= link_to 'Edit Game Category', edit_category_path(@category), :class => "lnk-button full" %>
					<%= link_to 'Destroy Game Category', @category, method: :delete, data: { confirm: 'Are you sure? This will destory all items under this category as well. It is recommended to just change the visibilty of the category.' }, :class => "lnk-button full cancel" %>
				</div>

				<h5>Hidden Games</h5>
				<ul class="unstyled">
					<% @category.games.where(:visible => false).each do |game| %>
						<li><strong><%= link_to game.name, edit_game_path(game) -%></strong></li>
					<% end %>
				</ul>
				
				<h5>All Hidden Games</h5>
				<ul class="unstyled lined">
					<% @all_hidden.each do |game| %>
						<li><strong><%= link_to game.name, edit_game_path(game) -%></strong><br/>In <%= game.category.name -%></li>
					<% end %>
				</ul>
				<div class="text-right"><%= link_to "See All Hidden Items", hidden_play_path %></div>
			<% else %>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'Go Back', play_path, :class => "lnk-button full" %>
				</div>
				<%= render 'shared/wannaplay' %>				
			<% end %>
		<% end %>
	</div>
	
</div>

app/views/categories/show.mobile.erb
<% title @category.name %>

<!-- Standard Content -->
<div class="content">
	<% if @category.area == "drinks" %>
		<div class="span12-12"><h3><i class="fa fa-beer"></i> Drinks<small>Gaming without poitions...wrong.</small></h3></div>
	<% elsif @category.area == "games" %>
		<div class="span12-12"><h3><i class="fa fa-gamepad"></i> Games<small>Achievement Unlocked!</small></h3></div>
	<% end %>
	
	<div class="span12-12">
		<h4><%= @category.name -%><small><%= @category.description -%></small></h4>
		
		<ul class="unstyled pad">
			<% if @category.area == "drinks" %>
				<% @category.drinks.where(:visible => true).order(name: :asc).each do |drink| %>
					<% if drink.call_out? %>
					<li class="callout_box">
					<% else %>
					<li>
					<% end %>
						<strong class="large"><div class="thumbnail-image text-center"><%= image_tag drink.drink_image.thumb -%></div>  <%= link_to drink.name, drink_path(drink) -%></strong><div><div class="float-right"><% if drink.price > 0 -%><%= number_to_currency drink.price -%><% end -%></div><%= drink.beer_style.name -%></div>
					</li>
				<% end %>
			<% elsif @category.area == "games" %>
				<% @category.games.where(:visible => true).order(name: :asc).each do |game| %>
					<li>
						<strong class="large"><div class="thumbnail-image text-center"><%= image_tag game.cover_art.thumb -%></div>  <%= link_to game.name, game_path(game) -%></strong><%= simple_format truncate game.description, length: 128 -%>
					</li>
				<% end %>
			<% end %>
		</ul>
	</div>
	
	<div class="span12-12">
		<% if @category.area == "drinks" %>
			<%= render 'shared/drink_search_form' %>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'Go Back', beverages_path, :class => "lnk-button full" %>
				</div>
		<% elsif @category.area == "games" %>
			<%= render 'shared/game_search_form' %>
				<div class="dq-buttons pad-bottom">
					<%= link_to 'Go Back', play_path, :class => "lnk-button full" %>
				</div>
		<% end %>
	</div>
	
</div>

app/views/categories/show_by_dispense_type.html.erb
<% title @dispense_type_name[params[:dispense_type]] %>

<!-- Standard Content -->
<div class="content">
	<div class="span12-12"><h2><i class="fa fa-beer"></i> Drinks<small>Gaming without poitions...wrong.</small></h2></div>
	
	<div class="span8-12">
		<h4><%= @dispense_type_name[params[:dispense_type].to_i] -%><small>Here is what we got.</small></h4>
		
		<%= @dispense_type_name %>
		
		<ul class="unstyled">
			<% @drinks.where(:visible => true).order(name: :asc).each do |drink| %>
				<% if drink.call_out? %>
				<li class="callout_box">
				<% else %>
				<li>
				<% end %>
					<strong class="large"><div class="thumbnail-image"><%= image_tag drink.drink_image.thumb -%></div>  <%= link_to drink.name, drink_path(drink) -%><div class="small"><%= drink.brewery -%></div></strong><%= simple_format drink.description -%>
					<% if admin_signed_in? -%><div class="text-right">Image: <%= drink.drink_image? -%> | Average Rating: <%= raw star_view drink.average_rating -%> | <%= link_to 'Edit', edit_drink_path(drink) %> | <%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></div><% end -%>
				</li>
			<% end %>
		</ul>
	</div>
	
	<div class="span4-12">
		<%= render 'shared/drink_search_form' %>
		<% if admin_signed_in? %>
			<h5>Admin Options</h5>
			<div class="dq-buttons pad-bottom">
				<%= link_to 'Go Back to Categories', beverages_path, :class => "lnk-button full back" %>

				<%= link_to 'Add New Drink to this Category', new_drink_path(:category_id => 3), :class => "lnk-button full pad-space new" %>
			</div>
			<h5>Hidden Drinks</h5>
			<ul class="unstyled lined">
				<% @drinks.where(:visible => false).each do |drink| %>
					<li><strong><%= link_to drink.name, edit_drink_path(drink) -%></strong></li>
				<% end %>
			</ul>
			
			<h5>All Hidden Drinks</h5>
			<ul class="unstyled lined">
				<% @all_hidden.each do |drink| %>
					<li><strong><%= link_to drink.name, edit_drink_path(drink) -%></strong><br/>In <%= drink.category.name -%></li>
				<% end %>
			</ul>
			<div class="text-right"><%= link_to "See All Hidden Items", hidden_beverages_path %></div>
		<% else %>
			<div class="dq-buttons pad-bottom">
				<%= link_to 'Go Back', beverages_path, :class => "lnk-button full" %>
			</div>
			<%= render 'shared/whycraft' %>
		<% end %>
	</div>
	
</div>